package com.example.vaultmusic.repository.impl.orm.room.dbo

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Database entity representing a music album.
 *
 * @property id The autogenerated unique primary key.
 * @property title The title of the album.
 * @property artistId Foreign key linking to [ArtistDbo].
 * @property releaseDate Unix timestamp (in milliseconds) of the album's release date.
 * @property coverPath Relative local file path from the app's directory to the album's cover image.
 *
 * @author macra21
 */
@Entity(
    tableName = "ALBUMS",
    foreignKeys = [
        ForeignKey(
            entity = ArtistDbo::class,
            parentColumns = ["id"],
            childColumns = ["artistId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class AlbumDbo(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val title: String,
    val artistId: Long,
    val releaseDate: Long?,
    val coverPath: String?
)
