package com.example.vaultmusic.repository.impl.orm.room.dbo

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Database entity representing a user created playlist.
 *
 * @property id The autogenerated unique primary key.
 * @property name The name of the playlist.
 * @property creationDate Unix timestamp (in milliseconds) of the playlist's creation date.
 * @property coverPath Relative local file path from the app's directory to the playlist's cover image.
 *
 * @author macra21
 */
@Entity(tableName = "PLAYLISTS")
data class PlaylistDbo(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val name: String,
    val creationDate: Long,
    val coverPath: String?
)
