package com.example.vaultmusic.repository.impl.orm.room.dbo

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Database entity representing an individual audio track.
 *
 * @property id The autogenerated unique primary key.
 * @property title The display title of the song.
 * @property artistId Foreign key linking to [ArtistDbo].
 * @property albumId Foreign key linking to [AlbumDbo].
 * @property filePath Absolute local file path where the audio file is stored.
 * @property duration Length of the song in seconds.
 * @property trackNumber The position of the song within its album.
 * @property description Additional metadata or lyrics.
 * @property releaseDate Unix timestamp of the song's release date.
 * @property coverPath Relative local file path to the song's cover image.
 *
 * @author macra21
 */
@Entity(
    tableName = "SONGS",
    foreignKeys = [
        ForeignKey(
            entity = ArtistDbo::class,
            parentColumns = ["id"],
            childColumns = ["artistId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = AlbumDbo::class,
            parentColumns = ["id"],
            childColumns = ["albumId"],
            onDelete = ForeignKey.CASCADE)
    ]
)
data class SongDbo(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L,
    val title: String,
    val artistId: Long,
    val albumId: Long,
    val filePath: String,
    val duration: Double,
    val trackNumber: Int,
    val description: String,
    val releaseDate: Long?,
    val coverPath: String?
)
