package com.example.vaultmusic.repository.impl.databases.room.dbo

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Database entity representing a musical artist.
 *
 * @property id The autogenerated unique primary key.
 * @property name The display name of the artist.
 * @property debutDate Unix timestamp (in milliseconds) of the artist's first release.
 * @property coverPath Relative local file path from the app's directory to the artist's cover image.
 *
 * @author macra21
 */
@Entity(tableName = "ARTISTS")
data class ArtistDbo(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val name: String,
    val debutDate: Long?,
    val coverPath: String?
)
